const $EventBuses = Java.loadClass("dev.architectury.platform.forge.EventBuses")
const $InfuseTypeDeferredRegister = Java.loadClass("mekanism.common.registration.impl.InfuseTypeDeferredRegister")
const INFUSETYPE = new $InfuseTypeDeferredRegister("kubejs")
INFUSETYPE.register("silicon", 0xF8F8FF)
INFUSETYPE.register("constantan", 0x9C7E6B)
INFUSETYPE.register("nickel", 0xDDD78C)
INFUSETYPE.register("scarlet_neodymium", 0xAA0000)
INFUSETYPE.register("azure_neodymium", 0x0000AA)
INFUSETYPE.register("blue_steel", 0x007FFF)
INFUSETYPE.register($EventBuses.getModEventBus("kubejs").get())