
#Mob Configuration
[mob_configuration]
	#Enable the default ability of Icy Creeper Explosions to grief the environment. 
	#If you prefer their explosions to not damage the environment, disable this feature. [true / false]
	enablyIcyCreeperGriefing = true

	#Vanilla Mob Configuration
	[mob_configuration.vanilla_mob_configuration]
		#Enable the addition of additional attributes to Husks to make them as powerful as they are in Minecraft Dungeons. [true / false]
		enableStrongerHusks = true
		#Enables Spiders and Cave Spiders shooting webs as a ranged attack like they do in Minecraft Dungeons. [true / false]
		enableRangedSpiders = false
		#Makes Mooshrooms hostile, like in Minecraft Dungeons. [true / false]
		enableHostileMooshrooms = true

